CREATE TABLE shipping_return (
    id INT AUTO_INCREMENT PRIMARY KEY,
    left_title VARCHAR(255) DEFAULT NULL,
    left_content TEXT DEFAULT NULL,
    right_title VARCHAR(255) DEFAULT NULL,
    right_content TEXT DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);