CREATE TABLE terms_condition_title (
    id INT AUTO_INCREMENT PRIMARY KEY,
    left_title VARCHAR(255) NOT NULL,
    right_title VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);